"use client";

import { useState, useEffect } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useTheme } from "next-themes";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TEMPLATES, Template } from "@/lib/templates";
import { NETWORKS, fetchAbiFromExplorer } from "@/lib/networks";
import { parseAbi, generateServerPy, generateRequirementsTxt, AbiItem, extractTools, GeneratedTool } from "@/lib/generator";

export default function TemplatePage() {
  const params = useParams();
  const { theme, setTheme } = useTheme();
  const [template, setTemplate] = useState<Template | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [mounted, setMounted] = useState(false);
  const [previewTools, setPreviewTools] = useState<GeneratedTool[]>([]);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);

  useEffect(() => {
    setMounted(true);
    const found = TEMPLATES.find(t => t.id === params.id);
    if (found) {
      setTemplate(found);
    }
  }, [params.id]);

  // Load tool preview for the first contract
  const loadToolPreview = async () => {
    if (!template || previewTools.length > 0 || isLoadingPreview) return;
    
    const firstContract = template.contracts[0];
    const network = NETWORKS.find(n => n.id === firstContract.network);
    if (!network?.explorerApi) return;

    setIsLoadingPreview(true);
    try {
      const abi = await fetchAbiFromExplorer(firstContract.address, network.explorerApi, network.chainId);
      const parsed = parseAbi(abi);
      const tools = extractTools(parsed);
      setPreviewTools(tools);
    } catch {
      // Silent fail - preview is optional
    } finally {
      setIsLoadingPreview(false);
    }
  };

  const handleGenerate = async () => {
    if (!template) return;
    
    setIsGenerating(true);

    try {
      const zip = new JSZip();
      const mcpServers: Record<string, unknown> = {};
      
      const failedContracts: string[] = [];
      let successCount = 0;
      
      for (const contract of template.contracts) {
        const contractNetwork = NETWORKS.find(n => n.id === contract.network);
        if (!contractNetwork?.explorerApi) {
          failedContracts.push(`${contract.name} (no explorer API for ${contract.network})`);
          continue;
        }

        try {
          const contractAbi = await fetchAbiFromExplorer(contract.address, contractNetwork.explorerApi, contractNetwork.chainId);
          const parsedAbi = parseAbi(contractAbi) as AbiItem[];
          
          const serverName = contract.name.toLowerCase().replace(/\s+/g, "-");
          const serverPy = generateServerPy(contract.name, contract.address, contractNetwork.rpcUrl, parsedAbi);
          
          zip.file(`${serverName}/server.py`, serverPy);
          zip.file(`${serverName}/abi.json`, JSON.stringify(parsedAbi, null, 2));
          zip.file(`${serverName}/requirements.txt`, generateRequirementsTxt());
          
          mcpServers[serverName] = {
            command: "python",
            args: [`${serverName}/server.py`],
            env: {
              RPC_URL: contractNetwork.rpcUrl,
            },
          };
          successCount++;
        } catch (contractErr) {
          const errMsg = contractErr instanceof Error ? contractErr.message : "Unknown error";
          failedContracts.push(`${contract.name}: ${errMsg}`);
        }
      }

      if (successCount === 0) {
        throw new Error(`Failed to fetch ABIs. Try again in a minute.`);
      }

      if (failedContracts.length > 0) {
        toast.warning(`Some contracts failed: ${failedContracts.join(", ")}`);
      }

      const templateReadme = `# ${template.name}

${template.icon} ${template.longDescription}

## Included Contracts

${template.contracts.map(c => `- **${c.name}** (${c.address.slice(0, 10)}...): ${c.description}`).join("\n")}

## Sample Prompts

${template.samplePrompts.map(p => `- "${p}"`).join("\n")}

## Setup

1. Install dependencies for each server:
\`\`\`bash
${template.contracts.map(c => `cd ${c.name.toLowerCase().replace(/\s+/g, "-")} && pip install -r requirements.txt && cd ..`).join("\n")}
\`\`\`

2. Add to Claude Desktop config:
\`\`\`json
${JSON.stringify({ mcpServers }, null, 2)}
\`\`\`

3. Restart Claude Desktop

---
Generated by [UCAI](https://github.com/nirholas/UCAI)
`;

      zip.file("README.md", templateReadme);
      zip.file("claude_config.json", JSON.stringify({ mcpServers }, null, 2));

      const blob = await zip.generateAsync({ type: "blob" });
      saveAs(blob, `${template.id}-mcp-bundle.zip`);
      toast.success("Bundle downloaded!");
    } catch (err) {
      const message = err instanceof Error ? err.message : "Failed to generate";
      toast.error(message);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!mounted) {
    return (
      <main className="min-h-screen bg-white dark:bg-slate-950">
        <div className="max-w-6xl mx-auto px-6 py-8">
          <Skeleton className="h-8 w-32 mb-8" />
          <Skeleton className="h-16 w-16 rounded-2xl mb-4" />
          <Skeleton className="h-8 w-64 mb-2" />
          <Skeleton className="h-4 w-96" />
        </div>
      </main>
    );
  }

  if (!template) {
    return (
      <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
        <div className="max-w-6xl mx-auto px-6 py-20 text-center">
          <h1 className="text-2xl font-bold text-slate-800 dark:text-slate-200 mb-4">Template not found</h1>
          <Link href="/"><Button>Back to Home</Button></Link>
        </div>
      </main>
    );
  }

  const relatedTemplates = TEMPLATES.filter(t => t.category === template.category && t.id !== template.id).slice(0, 3);
  const uniqueNetworks = [...new Set(template.contracts.map(c => c.network))];

  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950 flex flex-col">
      {/* Header */}
      <header className="border-b border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-6">
            <Link href="/" className="text-xl font-bold text-slate-800 dark:text-slate-100">
              UCAI
            </Link>
            <nav className="hidden md:flex items-center gap-4">
              <Link href="/" className="text-sm text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200 transition-colors">
                Templates
              </Link>
              <Link href="/community" className="text-sm text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200 transition-colors">
                Community
              </Link>
              <a href="https://docs.ucai.tech" target="_blank" className="text-sm text-slate-600 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200 transition-colors">
                Docs
              </a>
            </nav>
          </div>
          <div className="flex items-center gap-3">
            <a href="https://github.com/nirholas/UCAI" target="_blank" className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300">
              GitHub
            </a>
            <button
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
              className="p-2 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
            >
              {theme === "dark" ? <span>☀️</span> : <span>🌙</span>}
            </button>
          </div>
        </div>
      </header>

      {/* Hero CTA Section */}
      <div className="bg-gradient-to-r from-slate-800 to-slate-900 dark:from-slate-800 dark:to-slate-900 text-white">
        <div className="max-w-6xl mx-auto px-6 py-8">
          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
            <div className="flex items-center gap-5">
              <div className="w-16 h-16 rounded-2xl bg-white/10 backdrop-blur flex items-center justify-center text-4xl shrink-0">
                {template.icon}
              </div>
              <div>
                <div className="flex items-center gap-3 flex-wrap mb-1">
                  <h1 className="text-2xl font-bold">{template.name}</h1>
                  <Badge 
                    variant="outline"
                    className={
                      template.difficulty === "beginner" ? "bg-emerald-500/20 text-emerald-300 border-emerald-500/30" :
                      template.difficulty === "intermediate" ? "bg-amber-500/20 text-amber-300 border-amber-500/30" :
                      "bg-red-500/20 text-red-300 border-red-500/30"
                    }
                  >
                    {template.difficulty}
                  </Badge>
                </div>
                <p className="text-white/80">{template.description}</p>
              </div>
            </div>
            <div className="flex flex-col items-stretch md:items-end gap-2 w-full md:w-auto">
              <Button
                onClick={handleGenerate}
                disabled={isGenerating}
                size="lg"
                className="bg-white text-slate-900 hover:bg-slate-100 font-semibold px-8 shadow-lg"
              >
                {isGenerating ? "Generating..." : "Download MCP Bundle"}
              </Button>
              <p className="text-xs text-white/60 text-center md:text-right">
                {template.contracts.length} contract{template.contracts.length > 1 ? "s" : ""} • Ready for Claude Desktop
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Breadcrumb */}
      <div className="border-b border-slate-200 dark:border-slate-800 bg-white/50 dark:bg-slate-900/50">
        <div className="max-w-6xl mx-auto px-6 py-2">
          <div className="flex items-center gap-2 text-sm text-slate-500">
            <Link href="/" className="hover:text-slate-700 dark:hover:text-slate-300">Home</Link>
            <span>/</span>
            <Link href="/" className="hover:text-slate-700 dark:hover:text-slate-300">Templates</Link>
            <span>/</span>
            <span className="text-slate-700 dark:text-slate-300">{template.name}</span>
          </div>
        </div>
      </div>

      <div className="flex-1 max-w-6xl mx-auto px-6 py-8 w-full">
        <div className="grid grid-cols-1 lg:grid-cols-[1fr,320px] gap-8">
          {/* Main Content */}
          <div className="space-y-8">
            {/* Tabs */}
            <Tabs defaultValue="overview" className="w-full">
              <TabsList className="bg-slate-100 dark:bg-slate-800 p-1 rounded-lg">
                <TabsTrigger value="overview" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md">Overview</TabsTrigger>
                <TabsTrigger value="contracts" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md">Contracts</TabsTrigger>
                <TabsTrigger value="prompts" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md">Sample Prompts</TabsTrigger>
                <TabsTrigger value="tools" className="data-[state=active]:bg-white dark:data-[state=active]:bg-slate-700 rounded-md" onClick={loadToolPreview}>
                  Tool Preview
                </TabsTrigger>
              </TabsList>

              {/* Overview Tab */}
              <TabsContent value="overview" className="mt-6 space-y-6">
                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-3">About this template</h3>
                  <p className="text-slate-700 dark:text-slate-300 leading-relaxed">{template.longDescription}</p>
                </div>

                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Included Contracts</h3>
                  <div className="space-y-3">
                    {template.contracts.map((contract, idx) => {
                      const network = NETWORKS.find(n => n.id === contract.network);
                      return (
                        <div key={idx} className="flex items-center gap-3 p-3 rounded-lg bg-slate-50 dark:bg-slate-900/50">
                          <span className="text-lg">{network?.icon || "⬡"}</span>
                          <div className="flex-1 min-w-0">
                            <div className="font-medium text-slate-800 dark:text-slate-200">{contract.name}</div>
                            <div className="text-sm text-slate-500 dark:text-slate-400 truncate">{contract.description}</div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              </TabsContent>

              {/* Contracts Tab */}
              <TabsContent value="contracts" className="mt-6 space-y-4">
                {template.contracts.map((contract, idx) => {
                  const network = NETWORKS.find(n => n.id === contract.network);
                  return (
                    <div key={idx} className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                      <div className="flex items-start justify-between mb-4">
                        <div className="flex items-center gap-3">
                          <span className="text-2xl">{network?.icon || "⬡"}</span>
                          <div>
                            <h3 className="font-semibold text-slate-800 dark:text-slate-200">{contract.name}</h3>
                            <p className="text-sm text-slate-500 dark:text-slate-400">{network?.name || contract.network}</p>
                          </div>
                        </div>
                      </div>
                      
                      <p className="text-slate-600 dark:text-slate-400 mb-4">{contract.description}</p>
                      
                      <div className="flex items-center gap-2 p-3 rounded-lg bg-slate-50 dark:bg-slate-900/50">
                        <code className="flex-1 text-sm font-mono text-slate-600 dark:text-slate-300 truncate">
                          {contract.address}
                        </code>
                        <button
                          onClick={() => {
                            navigator.clipboard.writeText(contract.address);
                            toast.success("Copied!");
                          }}
                          className="text-sm text-slate-500 hover:text-slate-700 dark:hover:text-slate-300 shrink-0"
                        >
                          Copy
                        </button>
                      </div>
                    </div>
                  );
                })}
              </TabsContent>

              {/* Prompts Tab */}
              <TabsContent value="prompts" className="mt-6">
                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Try these with Claude</h3>
                  <div className="space-y-3">
                    {template.samplePrompts.map((prompt, idx) => (
                      <div 
                        key={idx}
                        className="group flex items-center justify-between p-4 rounded-lg bg-slate-50 dark:bg-slate-900/50 hover:bg-slate-100 dark:hover:bg-slate-900 transition-colors cursor-pointer"
                        onClick={() => {
                          navigator.clipboard.writeText(prompt);
                          toast.success("Prompt copied!");
                        }}
                      >
                        <p className="text-slate-700 dark:text-slate-300 italic">&ldquo;{prompt}&rdquo;</p>
                        <span className="text-xs text-slate-400 opacity-0 group-hover:opacity-100 transition-opacity">Click to copy</span>
                      </div>
                    ))}
                  </div>
                </div>
              </TabsContent>

              {/* Tools Preview Tab */}
              <TabsContent value="tools" className="mt-6">
                <div className="p-6 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
                  <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">
                    Generated Tools Preview
                  </h3>
                  {isLoadingPreview ? (
                    <div className="space-y-3">
                      <Skeleton className="h-10 w-full" />
                      <Skeleton className="h-10 w-full" />
                      <Skeleton className="h-10 w-3/4" />
                    </div>
                  ) : previewTools.length > 0 ? (
                    <div className="space-y-4">
                      <p className="text-sm text-slate-600 dark:text-slate-400 mb-4">
                        These are the Claude tools that will be generated from <strong>{template.contracts[0].name}</strong>:
                      </p>
                      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                        {previewTools.slice(0, 12).map((tool, idx) => (
                          <div 
                            key={idx}
                            className={`p-3 rounded-lg border text-sm ${
                              tool.type === "read" 
                                ? "bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800" 
                                : tool.type === "write"
                                ? "bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800"
                                : "bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800"
                            }`}
                          >
                            <div className="flex items-center gap-2">
                              <span className={`text-xs px-1.5 py-0.5 rounded ${
                                tool.type === "read" 
                                  ? "bg-emerald-100 dark:bg-emerald-800 text-emerald-700 dark:text-emerald-300" 
                                  : tool.type === "write"
                                  ? "bg-blue-100 dark:bg-blue-800 text-blue-700 dark:text-blue-300"
                                  : "bg-purple-100 dark:bg-purple-800 text-purple-700 dark:text-purple-300"
                              }`}>
                                {tool.type}
                              </span>
                              <span className="font-mono text-slate-700 dark:text-slate-300">{tool.name}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                      {previewTools.length > 12 && (
                        <p className="text-sm text-slate-500 text-center mt-4">
                          + {previewTools.length - 12} more tools
                        </p>
                      )}
                      <div className="flex gap-4 pt-4 border-t border-slate-200 dark:border-slate-700 mt-4 text-sm text-slate-600 dark:text-slate-400">
                        <span className="flex items-center gap-1">
                          <span className="w-2 h-2 rounded-full bg-emerald-500"></span>
                          Read: {previewTools.filter(t => t.type === "read").length}
                        </span>
                        <span className="flex items-center gap-1">
                          <span className="w-2 h-2 rounded-full bg-blue-500"></span>
                          Write: {previewTools.filter(t => t.type === "write").length}
                        </span>
                        <span className="flex items-center gap-1">
                          <span className="w-2 h-2 rounded-full bg-purple-500"></span>
                          Events: {previewTools.filter(t => t.type === "event").length}
                        </span>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-8">
                      <p className="text-slate-500 dark:text-slate-400 mb-4">Click to load a preview of generated tools</p>
                      <Button onClick={loadToolPreview} variant="outline">
                        Load Preview
                      </Button>
                    </div>
                  )}
                </div>
              </TabsContent>
            </Tabs>

            {/* Related Templates */}
            {relatedTemplates.length > 0 && (
              <div className="pt-8 border-t border-slate-200 dark:border-slate-800">
                <h3 className="text-sm font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-4">Related Templates</h3>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                  {relatedTemplates.map((related) => (
                    <Link key={related.id} href={`/templates/${related.id}`}>
                      <div className="p-4 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 hover:border-slate-300 dark:hover:border-slate-600 transition-colors">
                        <div className="flex items-center gap-3 mb-2">
                          <span className="text-xl">{related.icon}</span>
                          <span className="font-medium text-slate-800 dark:text-slate-200 text-sm">{related.name}</span>
                        </div>
                        <p className="text-xs text-slate-500 dark:text-slate-400 line-clamp-2">{related.description}</p>
                      </div>
                    </Link>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Sidebar */}
          <div className="space-y-4">
            {/* Quick Stats */}
            <div className="grid grid-cols-3 gap-2">
              <div className="p-3 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-center">
                <div className="text-2xl font-bold text-slate-800 dark:text-slate-200">{template.contracts.length}</div>
                <div className="text-xs text-slate-500 dark:text-slate-400">Contracts</div>
              </div>
              <div className="p-3 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-center">
                <div className="text-2xl font-bold text-slate-800 dark:text-slate-200">{template.samplePrompts.length}</div>
                <div className="text-xs text-slate-500 dark:text-slate-400">Prompts</div>
              </div>
              <div className="p-3 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700 text-center">
                <div className="text-2xl font-bold text-slate-800 dark:text-slate-200">{uniqueNetworks.length}</div>
                <div className="text-xs text-slate-500 dark:text-slate-400">Networks</div>
              </div>
            </div>

            {/* Networks */}
            <div className="p-4 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
              <h3 className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-3">Supported Networks</h3>
              <div className="flex flex-wrap gap-2">
                {uniqueNetworks.map(networkId => {
                  const network = NETWORKS.find(n => n.id === networkId);
                  return (
                    <div key={networkId} className="flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-900 text-sm">
                      <span>{network?.icon}</span>
                      <span className="text-slate-700 dark:text-slate-300">{network?.name || networkId}</span>
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Category & Difficulty */}
            <div className="p-4 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
              <div className="flex items-center justify-between mb-3">
                <span className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase">Category</span>
                <Badge variant="secondary" className="bg-slate-100 dark:bg-slate-700">{template.category}</Badge>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase">Difficulty</span>
                <Badge 
                  variant="outline"
                  className={
                    template.difficulty === "beginner" ? "bg-emerald-50 dark:bg-emerald-900/30 text-emerald-600 dark:text-emerald-400 border-emerald-200" :
                    template.difficulty === "intermediate" ? "bg-amber-50 dark:bg-amber-900/30 text-amber-600 dark:text-amber-400 border-amber-200" :
                    "bg-red-50 dark:bg-red-900/30 text-red-600 dark:text-red-400 border-red-200"
                  }
                >
                  {template.difficulty}
                </Badge>
              </div>
            </div>

            {/* Share */}
            <div className="p-4 rounded-xl bg-white dark:bg-slate-800/50 border border-slate-200 dark:border-slate-700">
              <h3 className="text-xs font-medium text-slate-500 dark:text-slate-400 uppercase tracking-wide mb-3">Share</h3>
              <div className="flex gap-2">
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="flex-1"
                  onClick={() => {
                    navigator.clipboard.writeText(window.location.href);
                    toast.success("Link copied!");
                  }}
                >
                  Copy Link
                </Button>
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="flex-1"
                  onClick={() => window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(`Check out the ${template.name} MCP template on UCAI! ${template.icon}\n\n${template.description}\n\nmcp.ucai.tech/templates/${template.id}`)}`, "_blank")}
                >
                  Tweet
                </Button>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-200 dark:border-slate-800 bg-white/50 dark:bg-slate-900/50 mt-auto">
        <div className="max-w-6xl mx-auto px-6 py-8">
          <div className="flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-slate-500 dark:text-slate-400">
            <div className="flex items-center gap-6">
              <Link href="/" className="font-semibold text-slate-800 dark:text-slate-200">UCAI</Link>
              <Link href="/" className="hover:text-slate-700 dark:hover:text-slate-200 transition-colors">Templates</Link>
              <Link href="/community" className="hover:text-slate-700 dark:hover:text-slate-200 transition-colors">Community</Link>
              <a href="https://docs.ucai.tech" target="_blank" className="hover:text-slate-700 dark:hover:text-slate-200 transition-colors">Documentation</a>
            </div>
            <div className="flex items-center gap-4">
              <a href="https://github.com/nirholas/UCAI" target="_blank" rel="noopener noreferrer" className="hover:text-slate-700 dark:hover:text-slate-200 transition-colors">GitHub</a>
              <a href="https://x.com/nichxbt" target="_blank" rel="noopener noreferrer" className="hover:text-slate-700 dark:hover:text-slate-200 transition-colors">𝕏</a>
              <span>Built by nich</span>
            </div>
          </div>
        </div>
      </footer>
    </main>
  );
}
